# Generated by Django 4.1 on 2022-08-22 19:44

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='MasterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=245, unique=True, verbose_name='Название')),
                ('subtitle', models.CharField(max_length=245, null=True, verbose_name='Под титул')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание мастеркласса')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Количество уроков')),
                ('amount_lessons', models.CharField(blank=True, max_length=200, null=True, verbose_name='Количество уроков')),
                ('image', models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('video', models.URLField(blank=True, null=True, verbose_name='Видео')),
                ('overview', models.TextField(verbose_name='Более подробное описание, мастер класса')),
                ('duration', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Продолжительность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('in_archive', models.BooleanField(default=False, verbose_name='В архив')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterclass.category', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Мастер Класс',
                'verbose_name_plural': 'Мастер Классы',
            },
        ),
    ]
