# Generated by Django 4.1 on 2022-08-30 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterclass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterclass',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterclass.category', verbose_name='Тема'),
        ),
    ]
