# Generated by Django 4.1 on 2022-09-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, help_text='0555055934', max_length=11, null=True, unique=True, verbose_name='Номер телефона'),
        ),
    ]
