# Generated by Django 4.1 on 2022-10-05 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterclass', '0002_alter_masterclass_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.PositiveSmallIntegerField(choices=[(10, 'Месяц'), (11, 'Половина курса'), (12, 'Полный курс')], default=10, verbose_name='Тип подписки')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Цена')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='course.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Пакет курса',
                'verbose_name_plural': 'Пакеты курсов',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок/Тип Оплаты')),
                ('description', models.TextField(verbose_name='Описание/Состав пакета')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Цена')),
                ('type', models.PositiveSmallIntegerField(choices=[(10, 'Месяц'), (13, 'Год'), (14, 'Год+')], default=10, verbose_name='Тип пакета')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Пакет',
                'verbose_name_plural': 'Пакеты',
            },
        ),
        migrations.CreateModel(
            name='RegisterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='Почта')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('payment_url', models.URLField(blank=True, null=True, verbose_name='Ссылка оплаты')),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID оплаты')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено?')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип пакета')),
                ('paid_price', models.CharField(blank=True, max_length=255, null=True, verbose_name='Конечная сумма')),
                ('status', models.CharField(choices=[('used', 'used'), ('expired', 'expired')], default='used', max_length=32, verbose_name='Статус подписки')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='Срок истечения')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Дата покупки')),
                ('package_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.package', verbose_name='Пакет')),
            ],
            options={
                'verbose_name': 'Заявка на регистрацию',
                'verbose_name_plural': 'Заявки на регистрации',
            },
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Активный?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки')),
                ('course_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.coursemembership', verbose_name='Подписка на курс')),
                ('register_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rg_membership', to='payments.registerrequest', verbose_name='Форма заявки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_membership', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='RegisterRequestPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Дата покупки')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='Срок истечения')),
                ('type', models.CharField(max_length=255, verbose_name='Тип пакета/Описание')),
                ('paid_price', models.CharField(blank=True, max_length=255, null=True, verbose_name='Конечная сумма')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('register_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rg_payments', to='payments.registerrequest', verbose_name='Заявка на регистрацию')),
            ],
            options={
                'verbose_name': 'Оплата пользователя',
                'verbose_name_plural': 'Оплаты пользователей',
            },
        ),
        migrations.CreateModel(
            name='MasterClassPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masterclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterclass.masterclass', verbose_name='Мастер-Класс')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.package', verbose_name='Пакет')),
            ],
        ),
        migrations.CreateModel(
            name='CoursePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='Курс')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_compound', to='payments.package', verbose_name='Пакет')),
            ],
        ),
    ]
